logging.level.com.example.shopping=DEBUG
spring.main.allow-circular-references=true
spring.datasource.url=jdbc:mysql://localhost:3306/shopping
spring.datasource.username=root
spring.datasource.password=seraku1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver